########### Config for Omnivla ###########
omnivla:
  # parameters for training dataset
  image_size: [224, 224] # width, height
  context_type: temporal
  normalize: True
  learn_angle: True
  num_workers: 10
  need_goal_img: False

########### Config for ViNT ###########
vint:
  # parameters for training dataset
  image_size: [224, 224] # width, height
  context_type: temporal
  normalize: True
  learn_angle: True
  num_workers: 10
  context_time: 0.3
  need_goal_img: True

########### Config for GNM ###########
gnm:
  # parameters for training dataset
  image_size: [224, 224] # width, height
  context_type: temporal
  normalize: True
  learn_angle: True
  num_workers: 10
  context_time: 0.3
  need_goal_img: True

########### Config for NoMAD ###########
nomad:
  # parameters for training dataset
  image_size: [224, 224] # width, height
  context_type: temporal
  normalize: True
  learn_angle: True
  num_workers: 10
  context_time: 0.3
  need_goal_img: True
